CREATE DATABASE doctor;
USE doctor;

-- DROP TABLE  doctorlist;
CREATE TABLE doctorlist (
    ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(45) NOT NULL,
    GENDER NVARCHAR(45),
    NATIONALITY NVARCHAR(45) NOT NULL,
    ADDRESS NVARCHAR(100) DEFAULT 'xxx',
    PHONE VARCHAR(20) DEFAULT '+84xxx',
    EDUCATION NVARCHAR(100) NOT NULL,
    POSITION NVARCHAR(255) NOT NULL,
    SPECIALIZED NVARCHAR(255) NOT NULL,
    HOSPITAL NVARCHAR(100) NOT NULL
);

-- DROP TABLE doctorinfo;
CREATE TABLE doctorinfo (
    ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(45),
    ADDRESS NVARCHAR(100),
    PHONE VARCHAR(20),
    EDUCATION NVARCHAR(100),
    POSITION NVARCHAR(255),
    HOSPITAL NVARCHAR(100),
    REWARD NVARCHAR(1000),
    EXPERIENCE NVARCHAR(1000),
    FOREIGN KEY (id) REFERENCES doctorlist(id)
);

-- DROP TRIGGER INFO ;
DELIMITER //
CREATE TRIGGER INFO AFTER
INSERT ON doctorlist
FOR EACH ROW
BEGIN
	INSERT INTO doctorinfo (Name,ADDRESS,PHONE,EDUCATION,POSITION,HOSPITAL)
		VALUES (new.NAME, new.ADDRESS, NEW.PHONE,NEW.EDUCATION,NEW.POSITION,NEW.HOSPITAL);
END//
#DELIMITER;
