CREATE DATABASE DOCTOR;
USE DOCTOR;


-- drop table DOCTORLIST;
CREATE TABLE DOCTORLIST (
    ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(45) NOT NULL,
    GIOITINH VARCHAR(45),
    QUOCTICH VARCHAR(45) NOT NULL,
    DIACHI VARCHAR(100) DEFAULT 'xxx',
    SODIENTHOAI VARCHAR(20) DEFAULT '+84xxx',
    HOCVAN VARCHAR(100) NOT NULL,
    CHUCVU VARCHAR(255) NOT NULL,
    CHUYENNGANH VARCHAR(255) NOT NULL,
    BENHVIEN VARCHAR(100) NOT NULL
);

-- drop table DOCTORINFO;
CREATE TABLE DOCTORINFO (
	ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(45),
    DIACHI VARCHAR(100),
    SODIENTHOAI VARCHAR(20),
    HOCVAN VARCHAR(100),
    CHUCVU VARCHAR(255),
    BENHVIEN VARCHAR(100),
    HOCVANVAGIAITHUONG VARCHAR(1000),
    KINHNGHIEMLAMVIEC VARCHAR(1000),
    foreign key (id) references doctorlist(id)
);

-- drop TRIGGER INFO ;
DELIMITER //
CREATE TRIGGER INFO after
INSERT ON doctorlist
FOR EACH ROW
begin
	insert into DOCTORINFO (TEN,DIACHI,SODIENTHOAI,HOCVAN,CHUCVU,BENHVIEN)
		values (new.TEN, new.DIACHI, NEW.SODIENTHOAI,NEW.HOCVAN,NEW.CHUCVU,NEW.BENHVIEN);
END//
#DELIMITER;

